# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diputacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['etapa'],
            },
        ),
        migrations.CreateModel(
            name='Fin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Generalitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subvencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('nombre', models.TextField(default='Subvenci\xf3n')),
                ('bases', models.TextField(blank=True, help_text='Enlace para las bases')),
                ('solicitud', models.TextField(blank=True, help_text='Enlace para la solicitud')),
                ('observaciones', models.TextField(blank=True, help_text='Enlace para observaciones')),
                ('ente', models.CharField(choices=[('DA', 'Diputaci\xf3n de Alicante'), ('GV', 'Generalitat Valenciana')], default=None, max_length=255)),
                ('cuantia', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('gestiona', models.TextField(blank=True, help_text='Enlace para el Gestiona')),
                ('gestiona_expediente', models.CharField(default='-', help_text='N\xfamero de expediente del Gestiona', max_length=250)),
                ('diputacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Diputacion')),
                ('estado', models.ForeignKey(default='Estado', on_delete=django.db.models.deletion.CASCADE, to='myapp.Estado')),
                ('fin', models.ManyToManyField(blank=True, to='myapp.Fin')),
                ('generalitat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Generalitat')),
                ('inicio', models.ManyToManyField(blank=True, to='myapp.Inicio')),
                ('responsable', models.ManyToManyField(blank=True, to='myapp.Responsable')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Subvencion',
                'verbose_name_plural': 'Subvenciones',
            },
        ),
    ]
