# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='se_relaciona_con',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Subvencion'),
        ),
    ]
