# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='fin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='inicio',
            field=models.CharField(default='', max_length=250),
        ),
    ]
