# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique=True),
        ),
    ]
