# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
