# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180201_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeRelacionCon',
        ),
        migrations.RemoveField(
            model_name='subvencion',
            name='se_relaciona_con',
        ),
        migrations.AddField(
            model_name='subvencion',
            name='se_relaciona_con',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='_subvencion_se_relaciona_con_+', to='myapp.Subvencion'),
        ),
    ]
