# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180123_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subvencion',
            old_name='gestiona',
            new_name='drive',
        ),
    ]
