# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180201_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='se_relaciona_con',
            field=models.ManyToManyField(blank=True, default='', related_name='_subvencion_se_relaciona_con_+', to='myapp.Subvencion'),
        ),
    ]
