# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180111_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique=True),
        ),
    ]
