# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 11:39
from __future__ import unicode_literals

from django.db import migrations
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180111_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='font_color',
            field=myapp.models.ColorField(blank=True, max_length=10),
        ),
    ]
