# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180228_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gobierno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('font_color', myapp.models.ColorField(blank=True, max_length=10)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='ente',
            field=models.CharField(choices=[('DA', 'Diputaci\xf3n de Alicante'), ('GV', 'Generalitat Valenciana'), ('GE', 'Gobierno de Espa\xf1a')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='subvencion',
            name='gobierno',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Gobierno'),
        ),
    ]
