# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 10:53
from __future__ import unicode_literals

from django.db import migrations
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_estado_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='diputacion',
            name='font_color',
            field=myapp.models.ColorField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='generalitat',
            name='font_color',
            field=myapp.models.ColorField(blank=True, max_length=10),
        ),
    ]
