# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180228_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subvencion',
            name='colectivo',
        ),
        migrations.AddField(
            model_name='subvencion',
            name='colectivo',
            field=models.ManyToManyField(blank=True, to='myapp.Colectivo'),
        ),
    ]
