# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180311_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subvencion',
            options={'ordering': ['fin'], 'verbose_name': 'Subvencion', 'verbose_name_plural': 'Subvenciones'},
        ),
    ]
