# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_subvencion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True),
        ),
    ]
