# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 12:45
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180415_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='comentarios',
            field=tinymce.models.HTMLField(),
        ),
    ]
