# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_responsable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
