# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_subvencion_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='subsidies_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
