# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180427_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subvencion',
            old_name='solicitud',
            new_name='bases',
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='procedimiento',
            field=models.TextField(blank=True, help_text='Enlace para los bases'),
        ),
    ]
