# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20180427_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subvencion',
            old_name='observaciones',
            new_name='Solicitud',
        ),
    ]
