# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20180427_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='cuantia_final',
            field=models.TextField(blank=True),
        ),
    ]
