# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_subvencion_cuantia_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='nombre_carpeta_drive',
            field=models.TextField(blank=True),
        ),
    ]
